# Generated by Django 5.1.3 on 2024-11-20 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_management', '0002_marklist_tc_course_student_fee_subject_internalmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='marklist',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_management.student'),
        ),
        migrations.AddField(
            model_name='tc',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_management.student'),
        ),
    ]
