# Generated by Django 5.1.3 on 2024-11-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_management', '0003_marklist_student_tc_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marklist',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='tc',
            name='reg_no',
        ),
    ]
